# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: blackmatrix. Edit fleet.json and regenerate — direct edits are overwritten.
#
# BlackMatrix — Node service.
#
# NOTE: Two reasons for host networking, both of which fail silently in bridge mode:
# the device scan sweeps the local /24s and would sweep Docker's bridge
# instead, and the Videohub emulation LISTENS on a port per switcher (9990
# upward) for panels to connect to. Devices can still be added by IP without
# the scan.

FROM node:22-slim AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production

# The whole built tree is copied, node_modules included. These are npm
# workspaces: pruning to production dependencies means re-resolving the
# workspace graph in the runtime stage, and getting that subtly wrong yields an
# image that starts and then throws MODULE_NOT_FOUND on the first request to
# whichever route needed the pruned package. Size is the price of not doing that.
COPY --from=builder /app ./

EXPOSE 8533
EXPOSE 9990
EXPOSE 9991
EXPOSE 9992

# A TCP connect, not an HTTP request against a guessed path. If this app grows a
# /health route the check can be tightened; asserting one that does not exist
# would mark a working container unhealthy forever.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "require('net').connect(8533,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))" || exit 1

CMD ["node", "packages/server/dist/index.js"]
